//Activities.js

const activities = [
  {
    id: 1,
    name: 'Tumon Beach',
    category: 'Beaches & Sightseeing',
    description: 'A beautiful white sand beach with crystal-clear waters, perfect for swimming and snorkeling.',
    provider: 'Tumon Beach Resort',
    website: 'https://www.tumonbeachresort.com',
  },
  {
    id: 2,
    name: 'Fish Eye Marine Park',
    category: 'Water Activities',
    description: 'A popular snorkeling spot with an underwater observatory and diverse marine life.',
    provider: 'Fish Eye Marine Park',
    website: 'https://www.fisheyemarinepark.com',
  },
  {
    id: 3,
    name: 'Two Lovers Point',
    category: 'Beaches & Sightseeing',
    description: 'A dramatic cliffside lookout with stunning views of Tumon Bay and the Philippine Sea.',
    provider: 'Two Lovers Point',
    website: 'https://www.twoloverspoint.com',
  },
  {
    id: 4,
    name: 'Tarzan Falls Hike',
    category: 'Hiking & Outdoor Adventures',
    description: 'A moderately difficult hike through the jungle to a beautiful waterfall.',
    provider: 'Guam Hiking Adventures',
    website: 'https://www.guamhikingadventures.com',
  },
  {
    id: 5,
    name: 'Talofofo Falls',
    category: 'Beaches & Sightseeing',
    description: 'A beautiful waterfall and park with a cable car, a small zoo, and other attractions.',
    provider: 'Talofofo Falls Park',
    website: 'https://www.talofofofallspark.com',
  },
  {
    id: 6,
    name: 'Cetti Bay Overlook',
    category: 'Beaches & Sightseeing',
    description: 'A scenic overlook with a stunning view of Cetti Bay.',
    provider: 'Guam Scenic Tours',
    website: 'https://www.guamscenictours.com',
  },
  {
    id: 7,
    name: 'Fish Eye Marine Park',
    category: 'Water Activities',
    description: 'A marine park with an underwater observatory, snorkeling, and scuba diving.',
    provider: 'Fish Eye Marine Park',
    website: 'https://www.fisheyemarinepark.com',
  },
  {
    id: 8,
    name: 'Valley of the Latte Adventure Park',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A cultural adventure park featuring a riverboat tour, botanical gardens, and traditional Chamorro activities.',
    provider: 'Valley of the Latte',
    website: 'https://www.valleyofthelatte.com',
  },
  {
    id: 9,
    name: 'Two Lovers Point',
    category: 'Beaches & Sightseeing',
    description: 'A famous scenic overlook with a panoramic view of Tumon Bay.',
    provider: 'Two Lovers Point',
    website: 'https://www.twoloverspoint.com',
  },
  {
    id: 10,
    name: 'Guam Beach and Culture Park',
    category: 'Cultural Experiences & Historical Sites',
    description: 'An outdoor park showcasing traditional Chamorro architecture and culture.',
    provider: 'Guam Beach and Culture Park',
    website: 'https://www.guambeachandculture'
  },
  {
    id: 11,
    name: 'War in the Pacific National Historical Park',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A national park dedicated to the history of World War II in the Pacific.',
    provider: 'National Park Service',
    website: 'https://www.nps.gov/wapa',
  },
  {
    id: 12,
    name: 'Guam National Wildlife Refuge Ritidian Unit',
    category: 'Hiking & Outdoor Adventures',
    description: 'A wildlife refuge with hiking trails, pristine beaches, and ancient Chamorro sites.',
    provider: 'U.S. Fish and Wildlife Service',
    website: 'https://www.fws.gov/refuge/Guam',
  },
  {
    id: 13,
    name: 'Mount Lamlam',
    category: 'Hiking & Outdoor Adventures',
    description: 'The highest peak in Guam, offering a challenging hike and stunning views.',
    provider: 'Guam Hiking Adventures',
    website: 'https://www.guamhikingadventures.com',
  },
  {
    id: 14,
    name: 'UnderWater World Guam',
    category: 'Water Activities',
    description: 'An aquarium featuring a walk-through underwater tunnel and a variety of marine life.',
    provider: 'UnderWater World Guam',
    website: 'https://www.uwwguam.com',
  },
  {
    id: 15,
    name: 'Dolphin Watching Cruise',
    category: 'Water Activities',
    description: 'A cruise offering the chance to see dolphins in their natural habitat.',
    provider: 'Dolphin Excursions Guam',
    website: 'https://www.dolphinexcursionsguam.com',
  },
  {
    id: 16,
    name: 'Fort Nuestra Senora de la Soledad',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A historic Spanish fort with beautiful views of the coast.',
    provider: 'Guam History Tours',
    website: 'https://www.guamhistorytours.com',
  },
  {
    id: 17,
    name: 'Gun Beach',
    category: 'Beaches & Sightseeing',
    description: 'A picturesque beach with snorkeling opportunities and a nearby WWII-era gun.',
    provider: 'Gun Beach Resort',
    website: 'https://www.gunbeachresort.com',
  },
  {
    id: 18,
    name: 'Ypao Beach Park',
    category: 'Beaches & Sightseeing',
    description: 'A popular beach park with picnic areas, playgrounds, and a nearby ancient Chamorro village.',
    provider: 'Ypao Beach Park',
    website: 'https://www.ypaobeachpark.com',
  },
  {
    id: 19,
    name: 'Scuba Diving in Apra Harbor',
    category: 'Water Activities',
    description: 'A scuba diving experience exploring the underwater world of Apra Harbor.',
    provider: 'Apra Harbor Diving Center',
    website: 'https://www.apraharbordivingcenter.com',
  },
  {
    id: 20,
    name: 'Pago Bay',
    category: 'Beaches & Sightseeing',
    description: 'A beautiful bay with a sandy beach and a lush, green backdrop.',
    provider: 'Pago Bay Resort',
    website: 'https://www.pagobayresort.com',
  },
  {
    id: 21,
    name: 'Guam Museum',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A museum showcasing the history and culture of Guam and its people.',
    provider: 'Guam Museum',
    website: 'https://www.guammuseum.org',
  },
  {
    id: 22,
    name: 'Chamorro Village Night Market',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A lively night market featuring local crafts, food, and entertainment.',
    provider: 'Chamorro Village',
    website: 'https://www.chamorro-village.com',
  },
  {
    id: 23,
    name: 'Taga Beach',
    category: 'Beaches & Sightseeing',
    description: 'A secluded beach with soft sand and crystal-clear waters, perfect for relaxation.',
    provider: 'Taga Beach Resort',
    website: 'https://www.tagabeachresort.com',
  },
  {
    id: 24,
    name: 'Kite Surfing at Matapang Beach',
    category: 'Water Activities',
    description: 'An exhilarating kite surfing experience at the beautiful Matapang Beach.',
    provider: 'Matapang Kite Surfing',
    website: 'https://www.matapangkitesurfing.com',
  },
  {
    id: 25,
    name: 'Guam Botanical Garden',
    category: 'Hiking & Outdoor Adventures',
    description: 'A peaceful botanical garden featuring native plants and walking trails.',
    provider: 'Guam Botanical Garden',
    website: 'https://www.guambotanicalgarden.com',
  },
  {
    id: 26,
    name: 'Fort Apugan',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A historic fort with panoramic views of Hagatna and the ocean.',
    provider: 'Guam History Tours',
    website: 'https://www.guamhistorytours.com',
  },
  {
    id: 27,
    name: 'Jungle Riverboat Cruise',
    category: 'Hiking & Outdoor Adventures',
    description: 'A scenic riverboat cruise through the lush jungles of Guam.',
    provider: 'Guam Jungle Cruises',
    website: 'https://www.guamjunglecruises.com',
  },
  {
    id: 28,
    name: 'Inarajan Natural Pools',
    category: 'Beaches & Sightseeing',
    description: 'A unique natural pool surrounded by volcanic rock formations.',
    provider: 'Inarajan Natural Pools',
    website: 'https://www.inarajannaturalpools.com',
  },
  {
    id: 29,
    name: 'Guam Seawalker Tours',
    category: 'Water Activities',
    description: 'A unique underwater walking experience with a special helmet that allows you to breathe normally.',
    provider: 'Guam Seawalker Tours',
    website: 'https://www.guamseawalkertours.com',
  },
  {
    id: 30,
    name: 'Latte Stone Park',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A park featuring ancient Chamorro latte stone pillars.',
    provider: 'Latte Stone Park',
    website: 'https://www.latte-stone-park.com',
  },
  {
    id: 31,
    name: 'Hagatna Heritage Walking Tour',
    category: 'Cultural Experiences & Historical Sites',
    description: 'A guided walking tour of Hagatna, exploring its rich history and cultural landmarks.',
    provider: 'Hagatna Heritage Tours',
    website: 'https://www.hagatnaheritagetours.com',
  },
  {
    id: 32,
    name: 'Guam Kayak and Snorkel Adventure',
    category: 'Water Activities',
    description: 'A fun-filled adventure combining kayaking and snorkeling along Guam\'s beautiful coastline.',
    provider: 'Guam Kayak and Snorkel',
    website: 'https://www.guamkayaksnorkel.com',
  },
  {
    id: 33,
    name: 'Asan Beach Park',
    category: 'Beaches & Sightseeing',
    description: 'A beach park with a rich WWII history, picnic areas, and walking trails.',
    provider: 'Asan Beach Park',
    website: 'https://www.asanbeachpark.com',
  },
  {
    id: 34,
    name: 'Ritidian Point',
    category: 'Beaches & Sightseeing',
    description: 'A remote, pristine beach with powdery white sand and crystal-clear waters.',
    provider: 'Ritidian Point Resort',
    website: 'https://www.ritidianpointresort.com',
  },
  {
    id: 35,
    name: 'Marbo Cave',
    category: 'Hiking & Outdoor Adventures',
    description: 'A natural limestone cave with a freshwater pool, perfect for swimming.',
    provider: 'Guam Hiking Adventures',
    website: 'https://www.guamhikingadventures.com',
  },
  {
    id: 36,
    name: 'Chamorro Cultural Workshop',
    category: 'Cultural Experiences & Historical Sites',
    description: 'An immersive workshop where you can learn about Chamorro culture, history, and traditional arts.',
    provider: 'Chamorro Cultural Center',
    website: 'https://www.chamorro-cultural-center.com',
  },
  {
    id: 37,
    name: 'Skydiving in Guam',
    category: 'Hiking & Outdoor Adventures',
    description: 'Experience the thrill of skydiving with breathtaking views of Guam\'s coastline.',
    provider: 'Guam Skydive Center',
    website: 'https://www.guamskydivecenter.com',
  },
  {
    id: 38,
    name: 'Merizo Pier',
    category: 'Beaches & Sightseeing',
    description: 'A picturesque pier perfect for fishing, picnicking, or enjoying the sunset.',
    provider: 'Merizo Pier',
    website: 'https://www.merizopier.com',
  },
  {
    id: 39,
    name: 'Stand Up Paddleboarding',
    category: 'Water Activities',
    description: 'Explore Guam\'s coastline on a stand-up paddleboard, perfect for all skill levels.',
    provider: 'Guam SUP Adventures',
    website: 'https://www.guamsupadventures.com',
  },
  {
    id: 40,
    name: 'Cocos Island Day Trip',
    category: 'Beaches & Sightseeing',
    description: 'A day trip to the beautiful Cocos Island, featuring stunning beaches and crystal-clear waters.',
    provider: 'Cocos Island Resort',
    website: 'https://www.cocosislandresort.com',
  },
]

export default activities;
